### ISSUE TITLE
Presets for Nodes

### ISSUE THREAD

**Issue by PhilippRigoll** [PhilippRigoll/osmapy#8]
Add a method to use presets for new nodes. Is there a external source where the presets can be loaded? Do we have to define them ourself? If we have to maybe a collection of yaml files for the objects would be cool.

**Comment by mfbehrens99** [comment]
I think they can be imported form [iD editor](https://github.com/openstreetmap/iD/tree/develop/data/presets). They have so called **fields** where you can enter the value for a specific key. A **presets** is simply a list of tags which should be added and all fields that should be available to change for the user.
Since iD is a very popular editor and is maintained we can also later pull newer versions of the presets library.

I am not sure in how far we can just use their library however I think it is good to not just create a new library that has to be maintained by the community.

**Comment by PhilippRigoll** [comment]
Hi! Thanks for contributing 👍 
That was also my first thought. Maybe we can add the iD repo as an git submodule. But then we have to checkout the whole iD repo... We also have to check where we have to put the copyright information of iD. The [Wiki](https://wiki.openstreetmap.org/wiki/Preset) states that "Go Map!!" also uses the iD presets. Perhaps we can learn there how too do it.

Personally I would prefer one storage of presets which is used by all editors. I'm not sure if there is a reason why it is not already done. It could be a Repo which everyone includes as a submodule. Or an API where the presets can be pulled. But I think we are too small to start an own repo which could be used by everyone. But we could suggest it to the others?

So as you suggested the first step would be to use the iDs presets. Is there better way than using git submodule?

**Comment by mfbehrens99** [comment]
Found something here: https://github.com/bryceco/GoMap/blob/master/src/presets/README.md

**Comment by Discostu36** [comment]
iD presets often don't comply to the community consensus as documented in the wiki. While using their presets might be a good starting point I think that this editor (if it really is supposed to become more than a proof of concept) should maintain its own library of presets.

**Comment by mfbehrens99** [comment]
I think it would make more sense to edit the iD presets to match the wiki documentation instead of creating some new ones

**Comment by Discostu36** [comment]
Yes, that's what I wanted to say.

**Comment by PhilippRigoll** [comment]
I created a fork of the iD presets and added them as a git submodule.
We should track the process of adding the Presets into Osmapy in separat issues. See for example #34 
Suggestions for next steps (issues) and contributions are welcome!
